version: "3.8"

services:
  keycloak:
    restart: always
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/realm-export.json
    command:
      - "-b 0.0.0.0"
    volumes:
      - "./realm-export.json:/opt/jboss/keycloak/realm-export.json"
